### ISSUE TITLE
where is the directoy for downloaded .jar files ?

### ISSUE THREAD

**Issue by balanx** [edwardcwang/chisel-single-file#1]
It works OK. Thanks very much !
I like the build way. It's easier than sbt.

But where is the directoy for downloaded dependency files ?
I can't find them in '~/.ammonite'.
Can I specify a path for them ?

thanks again

**Comment by edwardcwang** [comment]
Many Scala tools including ammonite and sbt use `~/.ivy2/cache` as a cache directory for downloaded JARs.

**Comment by edwardcwang** [comment]
Closing out of inactivity...
